apiVersion: v1
data:
  ACTIONS_ON_USERS_KAFKA_TOPIC: auth_service-registry_service
  ADULT_AGE_LIMIT: '18'
  API_ENABLE_DOCS: 'true'
  API_PREFIX: /api/v1
  APP_HOST: 0.0.0.0
  APP_PORT: '8002'
  AUTH_SERVICE_BASE_URL: https://api.dzhandosoft.kz/auth-service-orkendeu-project/api/v1
  BACKEND_CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:8000","http://127.0.0.1:3000","http://127.0.0.1:5173","https://127.0.0.1:5173","http://127.0.0.1:8000","http://0.0.0.0:3000","http://0.0.0.0:5173","http://0.0.0.0:8000","https://orkendeu.dzhandosoft.kz","https://api.dzhandosoft.kz/auth-service-orkendeu-project","https://api.dzhandosoft.kz/admin-module-orkendeu-project","https://api.dzhandosoft.kz/rpn-integration-service-orkendeu-project"]'
  DB_HOST: 10.0.0.17
  DB_NAME: registry_service_db
  DB_PORT: '5432'
  DB_USER: registry_module_user
  DEBUG: 'false'
  DEFAULT_LANGUAGE: ru
  KAFKA_BOOTSTRAP_SERVERS: '["kafka:9092"]'
  KAFKA_GROUP_ID: registry-service-users-group
  LANGUAGES: '["ru","kk","en"]'
  MAX_CONNECTIONS: '100'
  MAX_KEEPALIVE_CONNECTIONS: '10'
  MAX_OVERFLOW: '20'
  POOL_SIZE: '10'
  PROJECT_NAME: Registry Service [ORKENDEU]
  PROJECT_VERSION: dev-20250806-131952
  RPN_INTEGRATION_SERVICE_BASE_URL: https://rpn-integration-service:8010
  SCHEDULABLE_USER_ROLES: '["Chief Doctor","Primary Healthcare Expert","Registrar","General
    Practitioner","Specialist Doctor","Attending Physician"]'
  TIMEOUT: '5'
kind: ConfigMap
metadata:
  name: registry-config
