apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  DB_USER: registry_module_user
  DB_HOST: 10.0.0.17
  DB_PORT: "5432"
  DB_NAME: registry_service_db
  PROJECT_NAME: Registry Service [ORKENDEU]
  PROJECT_VERSION: 0.0.3
  API_PREFIX: /api/v1
  API_ENABLE_DOCS: "true"
  BACKEND_CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:8000","http://127.0.0.1:3000","http://127.0.0.1:5173","http://127.0.0.1:8000","http://0.0.0.0:3000","http://0.0.0.0:5173","http://0.0.0.0:8000","https://orkendeu.dzhandosoft.kz","https://api.dzhandosoft.kz/auth-service-orkendeu-project","https://api.dzhandosoft.kz/admin-module-orkendeu-project","https://api.dzhandosoft.kz/rpn-integration-service-orkendeu-project"]'
  DEBUG: "0"
  LANGUAGES: "[\"ru\",\"en\",\"kk\"]"
  DEFAULT_LANGUAGE: "ru"
  APP_HOST: 0.0.0.0
  APP_PORT: "8002"
  AUTH_SERVICE_BASE_URL: https://auth-service-app-dev:8001/api/v1
  RPN_INTEGRATION_SERVICE_BASE_URL: https://rpn-integration-service:8010
  TIMEOUT: "5"
  MAX_KEEPALIVE_CONNECTIONS: "10"
  MAX_CONNECTIONS: "100"
  KAFKA_BOOTSTRAP_SERVERS: '["kafka:9092"]'
  ACTIONS_ON_USERS_KAFKA_TOPIC: auth_service-registry_service
