"""empty message

Revision ID: a07c66b626f7
Revises: 281d106b1f65
Create Date: 2025-07-09 06:13:39.723525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07c66b626f7'
down_revision: Union[str, None] = '281d106b1f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stationary_assets', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stationary_assets', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
