"""empty message

Revision ID: d66917d6ba3f
Revises: b41530542aa6
Create Date: 2025-05-30 13:54:27.493800

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d66917d6ba3f"
down_revision: Union[str, None] = "b41530542aa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cat_citizenship",
        "name_ru",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="Citizenship name in Russian",
    )
    op.alter_column(
        "cat_citizenship",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="Citizenship name in English",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cat_citizenship",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="Citizenship name in English",
    )
    op.alter_column(
        "cat_citizenship",
        "name_ru",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="Citizenship name in Russian",
    )
    # ### end Alembic commands ###
