"""empty message

Revision ID: 1dc3cbbf1441
Revises: a07c66b626f7
Create Date: 2025-07-10 06:03:06.422225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc3cbbf1441'
down_revision: Union[str, None] = 'a07c66b626f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_organizations')
    op.drop_constraint('fk_stationary_assets_organization_id_cat_medical_organizations', 'stationary_assets', type_='foreignkey')
    op.drop_column('stationary_assets', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationary_assets', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_stationary_assets_organization_id_cat_medical_organizations', 'stationary_assets', 'cat_medical_organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_table('medical_organizations',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_medical_organizations'),
    sa.UniqueConstraint('code', name='uq_medical_organizations_code'),
    sa.UniqueConstraint('name', name='uq_medical_organizations_name')
    )
    # ### end Alembic commands ###
