"""empty message

Revision ID: 09265926cdbb
Revises: 50af45fe2e87
Create Date: 2025-06-17 11:37:24.883438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09265926cdbb"
down_revision: Union[str, None] = "50af45fe2e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_financing_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Financing source default name",
        ),
        sa.Column(
            "code",
            sa.String(length=20),
            nullable=False,
            comment="Financing source code",
        ),
        sa.Column(
            "lang",
            sa.String(length=5),
            nullable=False,
            comment="Financing source default language",
        ),
        sa.Column(
            "name_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Financing source's name additional locales",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat_financing_sources")),
        sa.UniqueConstraint("code", name=op.f("uq_cat_financing_sources_code")),
        sa.UniqueConstraint("name", name=op.f("uq_cat_financing_sources_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_financing_sources")
    # ### end Alembic commands ###
