"""empty message

Revision ID: d7e3e6270d2c
Revises: 377f0b796ea5
Create Date: 2025-06-13 14:44:28.822927

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7e3e6270d2c"
down_revision: Union[str, None] = "377f0b796ea5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Nationality default name",
        ),
    )
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "lang",
            sa.String(length=5),
            nullable=False,
            comment="Nationality default language",
        ),
    )
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "name_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Nationality's name additional locales",
        ),
    )
    op.drop_column("cat_nationalities", "name_kz")
    op.drop_column("cat_nationalities", "name_en")
    op.drop_column("cat_nationalities", "name_ru")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "name_ru",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Nationality name in Russian",
        ),
    )
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "name_en",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="id: int name in English",
        ),
    )
    op.add_column(
        "cat_nationalities",
        sa.Column(
            "name_kz",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="id: int name in Kazakh",
        ),
    )
    op.drop_column("cat_nationalities", "name_locales")
    op.drop_column("cat_nationalities", "lang")
    op.drop_column("cat_nationalities", "name")
    # ### end Alembic commands ###
