"""empty message

Revision ID: 377f0b796ea5
Revises: d66917d6ba3f
Create Date: 2025-06-10 11:36:26.373102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "377f0b796ea5"
down_revision: Union[str, None] = "d66917d6ba3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_nationalities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name_ru",
            sa.String(length=100),
            nullable=True,
            comment="Nationality name in Russian",
        ),
        sa.Column(
            "name_en",
            sa.String(length=100),
            nullable=False,
            comment="id: int name in English",
        ),
        sa.Column(
            "name_kz",
            sa.String(length=100),
            nullable=True,
            comment="id: int name in Kazakh",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat_nationalities")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_nationalities")
    # ### end Alembic commands ###
