"""empty message

Revision ID: 281d106b1f65
Revises: f508e57500da
Create Date: 2025-07-08 01:59:08.919842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281d106b1f65'
down_revision: Union[str, None] = 'f508e57500da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_medical_organizations_code')),
    sa.UniqueConstraint('name', name=op.f('uq_medical_organizations_name'))
    )
    op.add_column('stationary_assets', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('stationary_assets', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_stationary_assets_organization_id_cat_medical_organizations'), 'stationary_assets', 'cat_medical_organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_stationary_assets_patient_id_patients'), 'stationary_assets', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stationary_assets', 'patient_full_name')
    op.drop_column('stationary_assets', 'patient_birth_date')
    op.drop_column('stationary_assets', 'patient_iin')
    op.drop_column('stationary_assets', 'patient_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationary_assets', sa.Column('patient_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stationary_assets', sa.Column('patient_iin', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('stationary_assets', sa.Column('patient_birth_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('stationary_assets', sa.Column('patient_full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_stationary_assets_patient_id_patients'), 'stationary_assets', type_='foreignkey')
    op.drop_constraint(op.f('fk_stationary_assets_organization_id_cat_medical_organizations'), 'stationary_assets', type_='foreignkey')
    op.drop_column('stationary_assets', 'patient_id')
    op.drop_column('stationary_assets', 'organization_id')
    op.drop_table('medical_organizations')
    # ### end Alembic commands ###
