"""empty message

Revision ID: 50af45fe2e87
Revises: d66917d6ba3f
Create Date: 2025-06-11 13:46:16.797771

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50af45fe2e87"
down_revision: Union[str, None] = "d66917d6ba3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_patient_context_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Patient context attribute default name",
        ),
        sa.Column(
            "lang",
            sa.String(length=5),
            nullable=False,
            comment="Patient context attribute default language",
        ),
        sa.Column(
            "name_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Patient context attribute's name additional locales",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat_patient_context_attributes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_patient_context_attributes")
    # ### end Alembic commands ###
