"""empty message

Revision ID: b41530542aa6
Revises: 8d9295957a93
Create Date: 2025-05-30 13:53:11.620721

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b41530542aa6"
down_revision: Union[str, None] = "8d9295957a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name_kz",
            sa.String(length=100),
            nullable=True,
            comment="Citizenship name in Kazakh",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cat_citizenship", "name_kz")
    # ### end Alembic commands ###
