"""empty message

Revision ID: 4381bd754142
Revises: 50af45fe2e87
Create Date: 2025-06-16 11:20:00.801881

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4381bd754142"
down_revision: Union[str, None] = "50af45fe2e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_medical_organizations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "code",
            sa.String(length=20),
            nullable=False,
            comment="Medical organization internal code",
        ),
        sa.Column(
            "name",
            sa.String(length=256),
            nullable=False,
            comment="Medical organization default name",
        ),
        sa.Column(
            "address",
            sa.String(length=256),
            nullable=False,
            comment="Medical organization default address",
        ),
        sa.Column(
            "lang",
            sa.String(length=5),
            nullable=False,
            comment="Medical organization default language",
        ),
        sa.Column(
            "name_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Medical organization's name additional locales",
        ),
        sa.Column(
            "address_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Medical organization's address additional locales",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat_medical_organizations")),
        sa.UniqueConstraint("code", name=op.f("uq_cat_medical_organizations_code")),
        sa.UniqueConstraint("name", name=op.f("uq_cat_medical_organizations_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_medical_organizations")
    # ### end Alembic commands ###
