"""empty message

Revision ID: 0c629cf9773a
Revises: 18bd4362e19b
Create Date: 2025-06-30 16:05:19.011627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c629cf9773a'
down_revision: Union[str, None] = '18bd4362e19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_insurance_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=True, comment='Insurance policy number'),
    sa.Column('company', sa.String(length=100), nullable=True, comment='Insurance company name'),
    sa.Column('valid_from', sa.Date(), nullable=True, comment='Insurance valid from'),
    sa.Column('valid_till', sa.Date(), nullable=True, comment='Insurance valid till'),
    sa.Column('comment', sa.String(length=256), nullable=True, comment='Insurance comment'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Insurance ID'),
    sa.Column('financing_source_id', sa.Integer(), nullable=False, comment='Financing source ID'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financing_source_id'], ['cat_financing_sources.id'], name=op.f('fk_cat_insurance_info_financing_source_id_cat_financing_sources')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_cat_insurance_info_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_insurance_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat_insurance_info')
    # ### end Alembic commands ###
