"""empty message

Revision ID: 65292b44cdd2
Revises: f508e57500da
Create Date: 2025-07-08 15:30:54.936411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65292b44cdd2'
down_revision: Union[str, None] = 'f508e57500da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_code', sa.String(length=20), nullable=False, comment='Diagnosis code'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Diagnosis description'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_diagnoses')),
    sa.UniqueConstraint('diagnosis_code', name=op.f('uq_cat_diagnoses_diagnosis_code'))
    )
    op.create_table('patients_and_diagnoses',
    sa.Column('date_diagnosed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['cat_diagnoses.id'], name=op.f('fk_patients_and_diagnoses_diagnosis_id_cat_diagnoses')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_patients_and_diagnoses_doctor_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patients_and_diagnoses_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients_and_diagnoses'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_and_diagnoses')
    op.drop_table('cat_diagnoses')
    # ### end Alembic commands ###
