"""empty message

Revision ID: 029c941f52eb
Revises: 50af45fe2e87
Create Date: 2025-06-15 16:21:55.349632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "029c941f52eb"
down_revision: Union[str, None] = "50af45fe2e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Citizenship default name",
        ),
    )
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "lang",
            sa.String(length=5),
            nullable=False,
            comment="Citizenship default language",
        ),
    )
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name_locales",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Citizenship's name additional locales",
        ),
    )
    op.alter_column(
        "cat_citizenship",
        "country_code",
        existing_type=sa.VARCHAR(length=10),
        comment="Citizenship country code (ISO)",
        existing_comment="Country code (ISO)",
        existing_nullable=False,
    )
    op.drop_column("cat_citizenship", "name_ru")
    op.drop_column("cat_citizenship", "name_kz")
    op.drop_column("cat_citizenship", "name_en")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name_en",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="Citizenship name in English",
        ),
    )
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name_kz",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Citizenship name in Kazakh",
        ),
    )
    op.add_column(
        "cat_citizenship",
        sa.Column(
            "name_ru",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Citizenship name in Russian",
        ),
    )
    op.alter_column(
        "cat_citizenship",
        "country_code",
        existing_type=sa.VARCHAR(length=10),
        comment="Country code (ISO)",
        existing_comment="Citizenship country code (ISO)",
        existing_nullable=False,
    )
    op.drop_column("cat_citizenship", "name_locales")
    op.drop_column("cat_citizenship", "lang")
    op.drop_column("cat_citizenship", "name")
    # ### end Alembic commands ###
