"""empty message

Revision ID: 8d9295957a93
Revises: 8cb57a87b6d1
Create Date: 2025-05-30 13:23:47.317467

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d9295957a93"
down_revision: Union[str, None] = "8cb57a87b6d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_citizenship",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "country_code",
            sa.String(length=10),
            nullable=False,
            comment="Country code (ISO)",
        ),
        sa.Column(
            "name_ru",
            sa.String(length=100),
            nullable=False,
            comment="Citizenship name in Russian",
        ),
        sa.Column(
            "name_en",
            sa.String(length=100),
            nullable=True,
            comment="Citizenship name in English",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat_citizenship")),
        sa.UniqueConstraint(
            "country_code", name=op.f("uq_cat_citizenship_country_code")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_citizenship")
    # ### end Alembic commands ###
