"""empty message

Revision ID: 43ba04889f81
Revises: 3d6b6bd4181d
Create Date: 2025-07-28 14:15:01.845206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ba04889f81'
down_revision: Union[str, None] = '3d6b6bd4181d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('office_number', sa.Integer(), nullable=True))

    op.create_check_constraint(
        "ck_appointment_office_number_positive_or_null",
        "appointments",
        "(office_number IS NULL) OR (office_number >= 1)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'office_number')

    op.drop_constraint(
        "ck_appointment_office_number_positive_or_null",
        "appointments",
        type_="check"
    )
    # ### end Alembic commands ###
