"""empty message

Revision ID: d7b4ee75c124
Revises: 155d8530ab80
Create Date: 2025-08-08 10:39:55.736172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b4ee75c124'
down_revision: Union[str, None] = '155d8530ab80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_calls',
    sa.Column('call_number', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_address', sa.Text(), nullable=True),
    sa.Column('patient_phone', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_time', sa.Time(), nullable=False),
    sa.Column('registration_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time', sa.Time(), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('specialist', sa.String(length=255), nullable=False),
    sa.Column('is_insured', sa.Boolean(), nullable=False),
    sa.Column('has_oms', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('EGOV', 'CALL_PATIENT', 'APPLICATION', name='homecallsourceenum'), nullable=False),
    sa.Column('category', sa.Enum('EMERGENCY', 'URGENT', 'PLANNED', name='homecallcategoryenum'), nullable=False),
    sa.Column('reason', sa.Enum('ILLNESS', 'INJURY', 'CONSULTATION', 'VACCINATION', 'MEDICAL_CERTIFICATE', 'CHRONIC_DISEASE', 'ACUTE_CONDITION', 'PREVENTIVE_CARE', 'OTHER', name='homecallreasonenum'), nullable=False),
    sa.Column('call_type', sa.Enum('THERAPEUTIC', 'PEDIATRIC', 'SPECIALIST', 'NURSING', 'DIAGNOSTIC', name='homecalltypeenum'), nullable=False),
    sa.Column('reason_patient_words', sa.Text(), nullable=True),
    sa.Column('visit_type', sa.Enum('PRIMARY', 'REPEAT', name='homecallvisittypeenum'), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='homecallstatusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_home_calls_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_home_calls'))
    )
    op.create_index(op.f('ix_home_calls_call_number'), 'home_calls', ['call_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_calls_call_number'), table_name='home_calls')
    op.drop_table('home_calls')
    # ### end Alembic commands ###
