"""empty message

Revision ID: 3d6b6bd4181d
Revises: e9d6f8ab5b30
Create Date: 2025-07-21 09:38:47.996712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6b6bd4181d'
down_revision: Union[str, None] = 'e9d6f8ab5b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_identity_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('id_card', 'passport', 'birth_certificate', 'residence_permit', 'other', name='identity_document_type_enum'), nullable=False, comment='Identity document type'),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('issued_by', sa.String(length=256), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Patient ID'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_cat_identity_documents_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_identity_documents'))
    )

    op.add_column('patients', sa.Column('full_name', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_column('patients', 'full_name')

    op.drop_table('cat_identity_documents')
    # ### end Alembic commands ###
