"""empty message

Revision ID: 34ba89b6d1b7
Revises: 30c48ec5e208
Create Date: 2025-08-06 10:10:20.035139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34ba89b6d1b7'
down_revision: Union[str, None] = '30c48ec5e208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maternity_assets',
    sa.Column('bg_asset_id', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('receive_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receive_time', sa.Time(), nullable=False),
    sa.Column('actual_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_from', sa.String(length=255), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('stay_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stay_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stay_outcome', sa.String(length=50), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=True),
    sa.Column('stay_type', sa.String(length=50), nullable=True),
    sa.Column('patient_status', sa.String(length=50), nullable=True),
    sa.Column('diagnoses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список диагнозов в формате JSON'),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('specialist', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('REGISTERED', 'CONFIRMED', 'REFUSED', 'CANCELLED', name='assetstatusenum', create_type=False), nullable=False),
    sa.Column('delivery_status', postgresql.ENUM('RECEIVED_AUTOMATICALLY', 'PENDING_DELIVERY', 'DELIVERED', name='assetdeliverystatusenum', create_type=False), nullable=False),
    sa.Column('reg_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_confirm', sa.Boolean(), nullable=False),
    sa.Column('has_files', sa.Boolean(), nullable=False),
    sa.Column('has_refusal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_maternity_assets_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maternity_assets')),
    sa.UniqueConstraint('bg_asset_id', name=op.f('uq_maternity_assets_bg_asset_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maternity_assets')
    # ### end Alembic commands ###
