"""empty message

Revision ID: 155d8530ab80
Revises: 34ba89b6d1b7
Create Date: 2025-08-08 10:04:15.144876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155d8530ab80'
down_revision: Union[str, None] = '34ba89b6d1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sick_leaves',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_location_address', sa.Text(), nullable=True),
    sa.Column('receive_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receive_time', sa.Time(), nullable=False),
    sa.Column('actual_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_from', sa.String(length=255), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('workplace_name', sa.String(length=500), nullable=True),
    sa.Column('disability_start_date', sa.Date(), nullable=False),
    sa.Column('disability_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', 'EXTENSION', name='sickleavestatusenum'), nullable=False),
    sa.Column('sick_leave_reason', sa.Enum('ACUTE_ILLNESS', 'CHRONIC_ILLNESS', 'WORK_INJURY', 'DOMESTIC_INJURY', 'PREGNANCY_COMPLICATIONS', 'CHILD_CARE', 'FAMILY_MEMBER_CARE', name='sickleavereasonenum'), nullable=True),
    sa.Column('work_capacity', sa.Enum('TEMPORARILY_DISABLED', 'LIMITED_CAPACITY', 'TRANSFERRED_TO_LIGHT_WORK', name='workcapacityenum'), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('specialist', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('parent_sick_leave_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_sick_leave_id'], ['sick_leaves.id'], name=op.f('fk_sick_leaves_parent_sick_leave_id_sick_leaves')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_sick_leaves_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sick_leaves'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sick_leaves')
    # ### end Alembic commands ###
