"""Update user table

Revision ID: e06b10759b12
Revises: b1f3b3fff07b
Create Date: 2025-06-02 16:59:03.978110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e06b10759b12"
down_revision: Union[str, None] = "b1f3b3fff07b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "patient_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"adult": true, "child": false}',
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "referral_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"with_referral": true, "without_referral": true}',
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "referral_origins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"from_external_organization": true, "self_registration": true}',
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "payment_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"GOBMP": true, "DMS": true, "OSMS": true, "paid": true}',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "payment_types")
    op.drop_column("users", "referral_origins")
    op.drop_column("users", "referral_types")
    op.drop_column("users", "patient_types")
    # ### end Alembic commands ###
