"""empty message

Revision ID: bd4c644415f5
Revises: fdd33991acc8
Create Date: 2025-06-03 13:51:30.182407

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bd4c644415f5"
down_revision: Union[str, None] = "fdd33991acc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
