"""empty message

Revision ID: 904e7a1d8dd2
Revises: c86ff0d48e92
Create Date: 2025-04-11 14:51:06.630507

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "904e7a1d8dd2"
down_revision: Union[str, None] = "c86ff0d48e92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule_days", sa.Column("date", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_days", "date")
    # ### end Alembic commands ###
