"""empty message

Revision ID: 565af178f893
Revises: 2f42b74848e9
Create Date: 2025-06-04 11:06:31.726723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "565af178f893"
down_revision: Union[str, None] = "2f42b74848e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_rules")),
        sa.UniqueConstraint("key", name=op.f("uq_platform_rules_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_rules")
    # ### end Alembic commands ###
