"""empty message

Revision ID: d8e3d0dd8da2
Revises: da3e9a00d28b
Create Date: 2025-07-14 11:22:03.528245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e3d0dd8da2'
down_revision: Union[str, None] = 'da3e9a00d28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            CREATE TYPE appointment_status_enum AS ENUM ('free', 'booked', 'cancelled', 'appointment');
        """)
    op.execute("""
               ALTER TABLE appointments
               ALTER
               COLUMN status
            TYPE appointment_status_enum
            USING lower(status::text)::appointment_status_enum;
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
               ALTER TABLE appointments
               ALTER
               COLUMN status
            TYPE appointmentstatusenum
            USING upper(status::text)::appointmentstatusenum;
               """)
    op.execute("""
            DROP TYPE appointmentstatusenum;
        """)
    # ### end Alembic commands ###
