"""empty message

Revision ID: 49a8a76ea79f
Revises: 18bd4362e19b
Create Date: 2025-06-27 15:35:23.687964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a8a76ea79f'
down_revision: Union[str, None] = '18bd4362e19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_patient_id_users', 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_appointments_patient_id_patients'), 'appointments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_appointments_patient_id_patients'), 'appointments', type_='foreignkey')
    op.create_foreign_key('fk_appointments_patient_id_users', 'appointments', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
