"""empty message

Revision ID: 3c565c1c7233
Revises: a0b1b18d2639
Create Date: 2025-05-13 15:11:35.496320

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c565c1c7233"
down_revision: Union[str, None] = "a0b1b18d2639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_appointments_patient_id_users"),
        "appointments",
        "users",
        ["patient_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_schedules_doctor_id_users"),
        "schedules",
        "users",
        ["doctor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedules_doctor_id_users"), "schedules", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_appointments_patient_id_users"), "appointments", type_="foreignkey"
    )
    # ### end Alembic commands ###
