"""empty message

Revision ID: da3e9a00d28b
Revises: 14e3f3b12bef
Create Date: 2025-07-11 15:51:28.891893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3e9a00d28b'
down_revision: Union[str, None] = '14e3f3b12bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('appointments', sa.Column('financing_sources_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('appointments', 'type',
               existing_type=postgresql.ENUM('INITIAL', 'REVISIT', 'CONSULTATION', name='appointmenttypeenum'),
               nullable=True)
    op.alter_column('appointments', 'additional_services',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('appointments', 'insurance_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('insurance_type', postgresql.ENUM('GOBMP', 'DMS', 'OSMS', 'PAID', name='appointmentinsurancetype'), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'additional_services',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('appointments', 'type',
               existing_type=postgresql.ENUM('INITIAL', 'REVISIT', 'CONSULTATION', name='appointmenttypeenum'),
               nullable=False)
    op.drop_column('appointments', 'financing_sources_ids')
    op.drop_column('appointments', 'address')
    op.drop_column('appointments', 'phone_number')
    # ### end Alembic commands ###
