"""empty message

Revision ID: c86ff0d48e92
Revises: 65571d93e7e3
Create Date: 2025-04-09 16:53:09.664234

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c86ff0d48e92"
down_revision: Union[str, None] = "65571d93e7e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_days", sa.Column("appointment_interval", sa.Integer(), nullable=False)
    )
    op.drop_column("schedules", "appointment_interval")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "appointment_interval", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("schedule_days", "appointment_interval")
    # ### end Alembic commands ###
