"""empty message

Revision ID: 8cb57a87b6d1
Revises: 3c565c1c7233
Create Date: 2025-05-13 16:47:09.773096

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cb57a87b6d1"
down_revision: Union[str, None] = "3c565c1c7233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments", "patient_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments", "patient_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
