"""empty message

Revision ID: 86de0b4585a2
Revises: a83ef3209d00
Create Date: 2025-04-23 16:56:35.456460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86de0b4585a2"
down_revision: Union[str, None] = "a83ef3209d00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments", sa.Column("schedule_day_id", sa.UUID(), nullable=False)
    )
    op.add_column("appointments", sa.Column("time", sa.Time(), nullable=False))
    op.drop_constraint(
        "fk_appointments_schedule_id_schedules", "appointments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_appointments_schedule_day_id_schedule_days"),
        "appointments",
        "schedule_days",
        ["schedule_day_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("appointments", "appointment_date")
    op.drop_column("appointments", "schedule_id")
    op.drop_column("appointments", "appointment_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column(
            "appointment_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "appointments",
        sa.Column("schedule_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "appointments",
        sa.Column("appointment_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_appointments_schedule_day_id_schedule_days"),
        "appointments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_appointments_schedule_id_schedules",
        "appointments",
        "schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("appointments", "time")
    op.drop_column("appointments", "schedule_day_id")
    # ### end Alembic commands ###
