"""empty message

Revision ID: c9681993ff3a
Revises: 565af178f893
Create Date: 2025-06-04 13:58:02.487301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9681993ff3a"
down_revision: Union[str, None] = "565af178f893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules", sa.Column("description", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "description")
    # ### end Alembic commands ###
