"""empty message

Revision ID: a0b1b18d2639
Revises: 471284ea4ac0
Create Date: 2025-05-13 15:07:00.246533

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0b1b18d2639"
down_revision: Union[str, None] = "471284ea4ac0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_appointments_patient_id_users", "appointments", type_="foreignkey"
    )
    op.drop_constraint("fk_schedules_doctor_id_users", "schedules", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_schedules_doctor_id_users",
        "schedules",
        "users",
        ["doctor_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_appointments_patient_id_users",
        "appointments",
        "users",
        ["patient_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
