"""empty message

Revision ID: b1f3b3fff07b
Revises: 8cb57a87b6d1
Create Date: 2025-06-02 16:26:23.605786

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1f3b3fff07b"
down_revision: Union[str, None] = "8cb57a87b6d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Остальные команды миграции
    op.alter_column(
        "schedule_days",
        "work_start_time",
        existing_type=postgresql.TIME(),
        nullable=False,
    )
    op.alter_column(
        "schedule_days",
        "work_end_time",
        existing_type=postgresql.TIME(),
        nullable=False,
    )
    op.drop_column("schedule_days", "appointment_interval")

    # 1. Add column, allow NULL
    op.add_column(
        "schedules", sa.Column("appointment_interval", sa.Integer(), nullable=True)
    )
    # 2. Fill existing rows with default value (eg 30)
    op.execute("UPDATE schedules SET appointment_interval = 30")  # <-- default value!
    # 3. Make the column NOT NULL
    op.alter_column("schedules", "appointment_interval", nullable=False)

    op.drop_column("schedules", "patient_type")
    op.drop_column("schedules", "referral_types")
    op.drop_column("schedules", "payment_types")
    op.drop_column("schedules", "referral_origins")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "referral_origins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"self_registration": true, "from_external_organization": true}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "payment_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"DMS": true, "OSMS": true, "Paid": true, "GOBMP": true}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "referral_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"with_referral": true, "without_referral": true}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "patient_type",
            postgresql.ENUM("ADULT", "CHILD", name="schedulepatienttypeenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("schedules", "appointment_interval")
    op.add_column(
        "schedule_days",
        sa.Column(
            "appointment_interval", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "schedule_days", "work_end_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column(
        "schedule_days",
        "work_start_time",
        existing_type=postgresql.TIME(),
        nullable=True,
    )
    # ### end Alembic commands ###
